name: CI
on: [push, pull_request, workflow_dispatch]

jobs:
  legacy-CI:
    name: Legacy CI
    runs-on: ${{ matrix.operating-system }}
    services:
      mysql:
        image: mysql:5.7.27
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
        - 3306:3306
    strategy:
      max-parallel: 15
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['7.3', '7.4']
        shopware-versions: ['5.6', '5.5', '5.4']
        exclude:
          - php-versions: '7.4' 
            shopware-versions: '5.4'
          - php-versions: '7.4' 
            shopware-versions: '5.5'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: mbstring, xdebug, curl, dom, fileinfo, gd, iconv, intl, json, xml, pdo, phar, zip
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Check PHP Version
      run: php -v
    - name: PHP Syntax Checker
      run: find . -type f -name '*.php' -print0 | xargs -0 -n1 -P4 php -l -n | (! grep -v "No syntax errors detected" )
    - name: Install Shopware and Plugin
      run: |
        git clone --depth=1 -b ${{ matrix.shopware-versions }} https://github.com/shopware/shopware.git /tmp/shopware
        cd /tmp/shopware
        ant -f build/build.xml -Ddb.user=root -Ddb.password=root -Ddb.host=127.0.0.1 -Ddb.name=shopware build-unit
        cp -R $GITHUB_WORKSPACE/Frontend/MoptPaymentPayone /tmp/shopware/engine/Shopware/Plugins/Default/Frontend
        cd /tmp/shopware
        ls engine/Shopware/Plugins/Default/Frontend
        php bin/console sw:plugin:refresh
        php bin/console sw:plugin:list
        php bin/console sw:plugin:install MoptPaymentPayone
        php bin/console sw:plugin:activate MoptPaymentPayone
        php bin/console sw:generate:attributes
        php bin/console orm:generate:proxies
  current-CI:
    name: current CI
    runs-on: ${{ matrix.operating-system }}
    env:
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_NAME: shopware
      SW_HOST: localhost
      SW_BASE_PATH: ""
      ELASTICSEARCH_HOST: elasticsearch
    services:
      mysql:
        image: mysql:5.7.27
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: shopware
        ports:
        - 3306:3306
    strategy:
      max-parallel: 15
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['7.4', '8.0']
        shopware-versions: ['5.7']
        exclude:
          - php-versions: '8.0' 
            shopware-versions: '5.7'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: ctype, curl, dom, hash, iconv, gd, json, mbstring, openssl, session, simplexml, xml, zip, zlib, pdo, fileinfo
    - name: Check PHP Version
      run: php -v
    - name: PHP Syntax Checker
      run: find . -type f -name '*.php' -print0 | xargs -0 -n1 -P4 php -l -n | (! grep -v "No syntax errors detected" )
    - name: Install Shopware and Plugin
      run: |
        git clone --depth=1 -b ${{ matrix.shopware-versions }} https://github.com/shopware/shopware.git /tmp/shopware
        cd /tmp/shopware
        make init
        cp -R $GITHUB_WORKSPACE/Frontend/MoptPaymentPayone /tmp/shopware/engine/Shopware/Plugins/Default/Frontend
        cd /tmp/shopware
        ls engine/Shopware/Plugins/Default/Frontend
        php bin/console sw:plugin:refresh
        php bin/console sw:plugin:list
        php bin/console sw:plugin:install MoptPaymentPayone
        php bin/console sw:plugin:activate MoptPaymentPayone
        php bin/console sw:generate:attributes
        php bin/console orm:generate:proxies

